my first task
ArtPython/ArtPython pull request #8
Opened 2021-10-01 17:08 UTC by ArtPython

Check this please

2021-10-01 17:18 UTC, artmartm reviewed
123

2021-10-04 11:26 UTC, m4qo5 commented on iterator_tasks.py
> +        self.start = start - 1
Please, check that start and stop are numbers here, if it's not an instance of int then raise ValueError with an explanation.

2021-10-04 11:28 UTC, m4qo5 commented on iterator_tasks.py
> +# SECOND TASK
Please split different tasks and approaches into different files and name 'em accordingly

2021-10-04 11:28 UTC, m4qo5 commented on iterator_tasks.py
> +books = ['Atlas Shrugged', 'Tango with django ', 'Python crash course']
Please make this a function

2021-10-04 11:29 UTC, m4qo5 commented on iterator_tasks.py
> +        ic(book)
Please delete all the print statements from the code

2021-10-04 11:29 UTC, m4qo5 requested changes
Left a review

2021-10-04 11:55 UTC, ArtPython commented on iterator_tasks.py
> +        ic(book)
got it

2021-10-04 11:55 UTC, ArtPython commented on iterator_tasks.py
> +books = ['Atlas Shrugged', 'Tango with django ', 'Python crash course']
what do you mean?

2021-10-04 11:56 UTC, ArtPython commented on iterator_tasks.py
> +# SECOND TASK
got it

2021-10-04 11:56 UTC, ArtPython commented on iterator_tasks.py
> +        self.start = start - 1
got it

2021-10-04 12:51 UTC, ArtPython commented on iterator_tasks.py
> +books = ['Atlas Shrugged', 'Tango with django ', 'Python crash course']
I've figured it out, okay

2021-10-06 13:04 UTC, merged